WMRP/Controllers/GanttChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WMRP.Controllers
{
    public class GanttChartController : Controller
    {
        //
        // GET: /GanttChart/
        public ActionResult Index()
        {
            return View();
        }
	}
}

WMRP/Controllers/MasterSchedulerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WMRP.Service.IServices;
using WMRP.Service.Dto;



namespace WMRP.Controllers
{
    public class MasterSchedulerController : Controller
    {
        private readonly IManufactureOrderService _manufacturerOrderService;
        //
        // GET: /MasterScheduler/
        public MasterSchedulerController(IManufactureOrderService manufacturerOrderService)
        {
            _manufacturerOrderService = manufacturerOrderService;
        }
        public ActionResult Index()
        {
            return View();
        }

         public JsonResult GetEvents()
         {
             var events = _manufacturerOrderService.GetAllOrders().ToList();
             //var dateList = new List<DateTime>();
             //foreach (var item in events)
             //{
             //    dateList.Add(item.ExpectedStartDate);
             //    dateList.Add(item.ExpectedEndDate);
             //    dateList.Add(item.CalculatedCompletionDate);
             //}
             return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        [HttpPost]
        public JsonResult SaveEvent(ManufactureOrderViewModel manufactureOrderViewModel)
        {
            var response = _manufacturerOrderService.AddMOrder(manufactureOrderViewModel);
            return new JsonResult { Data = new { status = response.Message } };

        }

        

    }
}

WMRP/Views/GanttChart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CustomLayout.cshtml";
}

<style>
    #chartdiv {
        width: 100%;
        height: 200px;
    }
</style>
<div id="chartdiv"></div>
<!-- Resources -->
@*<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>*@
@section scripts{
    <script src="~/Scripts/am_core.js"></script>
    <script src="~/Scripts/am_charts.js"></script>
    <script src="~/Scripts/am_animated.js"></script>

    <!-- Chart code -->
    <script>

        var ganttChartData = [];
        
        $(document).ready(function () {

            getGanttChartData();

        });

        var getGanttChartData = function () {
            
            $.ajax({
                url: "@Url.Action("GetEvents", "MasterScheduler")",
                    type: 'GET',
                    contentType: 'application/json',
                    success: function(result) {
                    var dataset = [];
                    debugger;
                    $.each(result, function(key, value) {
                        var item = {};
                        item.category = value.Title;
                        item.start = value.ExpectedStartDateText;
                        item.end = value.CalculatedCompletionDateText;
                        item.color = value.BDColor;
                        //item.color = "#" + ((1 << 24) * Math.random() | 0).toString(16);
                        //item.task = value.ProductModelName;
                        //item.task = value.PackageName;
                        debugger;
                        if (value.ProductModelName === "") {

                            item.task = value.PackageName;
                        } else {

                            item.task = value.ProductModelName;
                        }

                        dataset.push(item);
                    });
                    debugger;
                    ganttChartData = JSON.parse(JSON.stringify(dataset));
                    loadGanttChart(ganttChartData);
                }
            });
        };

        // Themes begin
        am4core.useTheme(am4themes_animated);
        // Themes end
        var loadGanttChart = function(data) {
            var chart = am4core.create("chartdiv", am4charts.XYChart);
            chart.hiddenState.properties.opacity = 0; // this creates initial fade-in

            chart.paddingRight = 30;
            chart.dateFormatter.inputDateFormat = "yyyy-MM-dd HH:mm";

            var colorSet = new am4core.ColorSet();
            colorSet.saturation = 0.4;

            chart.data = data;

            chart.dateFormatter.dateFormat = "yyyy-MM-dd";
            chart.dateFormatter.inputDateFormat = "yyyy-MM-dd";

            var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
            categoryAxis.dataFields.category = "category";
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.renderer.inversed = true;

            var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
            dateAxis.renderer.minGridDistance = 50;
            dateAxis.baseInterval = { count: 1, timeUnit: "day" };
            // dateAxis.max = new Date(2018, 0, 1, 24, 0, 0, 0).getTime();
            //dateAxis.strictMinMax = true;
            dateAxis.renderer.tooltipLocation = 0;

            var series1 = chart.series.push(new am4charts.ColumnSeries());
            series1.columns.template.width = am4core.percent(80);
            series1.columns.template.tooltipText = "{task}: [bold]{openDateX}[/] - [bold]{dateX}[/]";

            series1.dataFields.openDateX = "start";
            series1.dataFields.dateX = "end";
            series1.dataFields.categoryY = "category";
            series1.columns.template.propertyFields.fill = "color"; // get color from data
            series1.columns.template.propertyFields.stroke = "color";
            series1.columns.template.strokeOpacity = 1;

            chart.scrollbarX = new am4core.Scrollbar();
        };

        
    </script>
}

<!-- HTML -->